id: A4EF9F6C7
base_file: f70A4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.016183
  last_modified_at: 2022-05-31 05:28:20.016186
