id: A4EF9F6C7
base_file: f8E43.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.037784
  last_modified_at: 2022-05-31 05:28:20.037787
