id: A4EF9F6C7
base_file: f3368.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.960598
  last_modified_at: 2022-05-31 05:28:19.960601
