id: A4EF9F6C7
base_file: fFC0D.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.099029
  last_modified_at: 2022-05-31 05:28:20.099045
