id: A4EF9F6C7
base_file: fD939.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.074543
  last_modified_at: 2022-05-31 05:28:20.074546
