id: A4EF9F6C7
base_file: f76AA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.020256
  last_modified_at: 2022-05-31 05:28:20.020259
