id: A4EF9F6C7
base_file: f14FD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.951237
  last_modified_at: 2022-05-31 05:28:19.951240
