id: A4EF9F6C7
base_file: f81DA.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.026785
  last_modified_at: 2022-05-31 05:28:20.026788
