id: A4EF9F6C7
base_file: f4044.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.971582
  last_modified_at: 2022-05-31 05:28:19.971585
