id: A4EF9F6C7
base_file: f7F63.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.024700
  last_modified_at: 2022-05-31 05:28:20.024703
