id: A4EF9F6C7
base_file: fB474.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.055542
  last_modified_at: 2022-05-31 05:28:20.055545
