id: A4EF9F6C7
base_file: f4986.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.995118
  last_modified_at: 2022-05-31 05:28:19.995122
