id: A4EF9F6C7
base_file: fCCDB.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.068915
  last_modified_at: 2022-05-31 05:28:20.068918
