id: A4EF9F6C7
base_file: f85A3.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.032293
  last_modified_at: 2022-05-31 05:28:20.032296
