id: A4EF9F6C7
base_file: f42F4.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.992315
  last_modified_at: 2022-05-31 05:28:19.992321
