id: A4EF9F6C7
base_file: f3DCC.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.968377
  last_modified_at: 2022-05-31 05:28:19.968380
