id: A4EF9F6C7
base_file: fC7A3.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.063854
  last_modified_at: 2022-05-31 05:28:20.063857
