id: A4EF9F6C7
base_file: fB8F8.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.059466
  last_modified_at: 2022-05-31 05:28:20.059469
