id: A4EF9F6C7
base_file: fA9AC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.049164
  last_modified_at: 2022-05-31 05:28:20.049166
