id: A4EF9F6C7
base_file: fFFF7.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.104746
  last_modified_at: 2022-05-31 05:28:20.104749
