id: A4EF9F6C7
base_file: f88ED.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.035470
  last_modified_at: 2022-05-31 05:28:20.035473
