id: A4EF9F6C7
base_file: f1218.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:19.949999
  last_modified_at: 2022-05-31 05:28:19.950002
