id: A4EF9F6C7
base_file: fFE99.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.100559
  last_modified_at: 2022-05-31 05:28:20.100562
