id: A4EF9F6C7
base_file: f5D73.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:28:20.010513
  last_modified_at: 2022-05-31 05:28:20.010516
